global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['edge3-prometheus:9090']
  - job_name: 'app'
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets: ['edge3-api:8000']
  - job_name: 'minio'
    scrape_interval: 15s
    metrics_path: /minio/v2/metrics/cluster
    static_configs:
      - targets: ['edge3-minio:9000']
  - job_name: 'mysql'
    scrape_interval: 15s
    static_configs:
      - targets: ['edge3-mysql-exporter:9104']
