services:
  minio-benchmark:
    image: "minio/minio:RELEASE.2025-07-23T15-54-02Z"
    ports:
      - "7000:9000" # ホスト7000 → コンテナ9000(API)
      - "7001:9090" # ホスト7001 → コンテナ9090(コンソール)
    env_file:
      - ./.env
    environment:
       MINIO_ROOT_USER: "${MINIO_ROOT_USER:-minio_root}"
       MINIO_ROOT_PASSWORD: "${MINIO_ROOT_PASSWORD:-minio_password}"
       MINIO_PROMETHEUS_AUTH_TYPE: "public"
    command: server /export --console-address ":9090"
    volumes:
      - minio-bench-data:/export
  minio-prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    ports:
      - 7090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  minio-grafana:
    image: grafana/grafana
    restart: unless-stopped
    depends_on:
      - minio-prometheus
    ports:
      - 3000:3000
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    env_file:
      - ./grafana/config.monitoring
      
volumes:
  minio-bench-data:
    name: minio-bench-data